services:  
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: ["8972:1972","8973:52773","8081:8080","8091:8090"]
    container_name: negation_aware_search_en
    volumes: ["./src:/src"]
    #runtime: nvidia
    environment:
      - TZ=JST-9
    #  - NVIDIA_VISIBLE_DEVICES=all
    #  - NVIDIA_DRIVER_CAPABILITIES=compute,utility

